[package]
name = "todo_api_rust"
version = "0.1.0"
authors = ["bl0rch1d <temaflash96@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
